import { CandidatesInterface } from './../models/interfaces'
import { Qualified } from './../models/enum'

export const candidates: CandidatesInterface = {
  items: [
    {
      id: 1,
      createdAt: '2020-10-27T13:49:26.927Z',
      fullName: 'Velma Funk',
      qualified: Qualified.InReview,
      phone: '178-882-2475',
      email: 'Ignacio18@hotmail.com',
      jobTitle: 'Direct Web Planner',
      country: 'Montserrat',
      jobLocation: 'Holdenmouth',
    },
    {
      id: 2,
      createdAt: '2020-10-27T14:22:27.203Z',
      fullName: 'Wendell Maggio',
      avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/baires/128.jpg',
      qualified: Qualified.InReview,
      phone: '092.807.6007 x310',
      email: 'Izabella.Watsica@gmail.com',
      jobTitle: 'Regional Response Manager',
      country: 'United States Minor Outlying Islands',
      jobLocation: 'Port Catherine',
    },
    {
      id: 3,
      createdAt: '2020-10-27T06:19:38.914Z',
      fullName: 'Silas Marks',
      avatar:
        'https://s3.amazonaws.com/uifaces/faces/twitter/iamjdeleon/128.jpg',
      qualified: Qualified.InReview,
      email: 'Peyton_Aufderhar@gmail.com',
      jobTitle: 'National Brand Producer',
      country: 'Ecuador',
      jobLocation: 'Port Shayna',
    },
    {
      id: 4,
      createdAt: '2020-10-27T19:19:56.799Z',
      fullName: 'Wayne Prosacco',
      avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/j2deme/128.jpg',
      qualified: Qualified.Yes,
      phone: '(340) 087-8581 x3735',
      email: 'Eloise21@gmail.com',
      jobTitle: 'Product Accountability Assistant',
      country: 'Peru',
      jobLocation: 'New Heath',
    },
    {
      id: 5,
      createdAt: '2020-10-27T14:15:35.536Z',
      fullName: 'Broderick Kshlerin',
      avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/mactopus/128.jpg',
      qualified: Qualified.No,
      phone: '632-952-3136',
      email: 'Myron_Predovic2@gmail.com',
      jobTitle: 'Forward Accountability Assistant',
      country: 'Antigua and Barbuda',
      jobLocation: 'Shieldsmouth',
    },
    {
      id: 6,
      createdAt: '2020-10-27T22:40:18.918Z',
      fullName: 'Catherine Gutmann DVM',
      avatar:
        'https://s3.amazonaws.com/uifaces/faces/twitter/jeremymouton/128.jpg',
      qualified: Qualified.Yes,
      email: 'Donavon0@yahoo.com',
      jobTitle: 'Dynamic Creative Specialist',
      country: 'Netherlands',
      jobLocation: 'Jaydonfurt',
    },
    {
      id: 7,
      createdAt: '2020-10-27T10:49:23.559Z',
      fullName: 'Bert Rice',
      avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/thimo_cz/128.jpg',
      qualified: Qualified.No,
      phone: '1-212-455-1556',
      email: 'Earline.Herzog@gmail.com',
      jobTitle: 'International Tactics Architect',
      country: 'Taiwan',
      jobLocation: 'Port Lisa',
    },
    {
      id: 8,
      createdAt: '2020-10-27T01:28:02.186Z',
      fullName: 'Theodore Flatley',
      avatar:
        'https://s3.amazonaws.com/uifaces/faces/twitter/terrorpixel/128.jpg',
      qualified: Qualified.No,
      email: 'Carrie.Legros@hotmail.com',
      jobTitle: 'Direct Tactics Associate',
      country: 'British Indian Ocean Territory (Chagos Archipelago)',
      jobLocation: 'Lake Cydney',
    },
    {
      id: 9,
      createdAt: '2020-10-27T22:31:24.829Z',
      fullName: 'Leila Moen',
      qualified: Qualified.Yes,
      phone: '(481) 910-1573',
      email: 'Chaz10@yahoo.com',
      jobTitle: 'Product Paradigm Producer',
      country: 'Saint Pierre and Miquelon',
      jobLocation: 'East Norberto',
    },
    {
      id: 10,
      createdAt: '2020-10-27T09:48:07.208Z',
      fullName: 'Dr. Jacky Blanda',
      avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/divya/128.jpg',
      qualified: Qualified.Yes,
      phone: '(820) 754-1840',
      email: 'Bobby.Becker71@yahoo.com',
      jobTitle: 'Human Communications Agent',
      country: 'Spain',
      jobLocation: 'Robelville',
    },
  ],
  count: 10,
  total: 10,
}
